# Generated by Django 5.1.15 on 2026-03-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecurringTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="タスク名")),
                ("description", models.TextField(blank=True, verbose_name="詳細メモ")),
                (
                    "cycle_months",
                    models.PositiveSmallIntegerField(verbose_name="実行周期（ヶ月）"),
                ),
                ("next_due_date", models.DateField(verbose_name="次回実行予定日")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "定期タスク",
                "verbose_name_plural": "定期タスク",
                "ordering": ["next_due_date"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="サービス名")),
                ("price", models.PositiveIntegerField(verbose_name="料金（円）")),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "毎月"),
                            ("yearly", "毎年"),
                            ("quarterly", "毎四半期"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="支払い周期",
                    ),
                ),
                ("next_billing_date", models.DateField(verbose_name="次回支払日")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "サブスクリプション",
                "verbose_name_plural": "サブスクリプション",
                "ordering": ["next_billing_date"],
            },
        ),
    ]
