# Generated by Django 5.1.15 on 2026-03-28 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringtask",
            name="cycle_months",
        ),
        migrations.AddField(
            model_name="recurringtask",
            name="day_of_week",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "月曜日"),
                    (1, "火曜日"),
                    (2, "水曜日"),
                    (3, "木曜日"),
                    (4, "金曜日"),
                    (5, "土曜日"),
                    (6, "日曜日"),
                ],
                null=True,
                verbose_name="指定曜日",
            ),
        ),
        migrations.AddField(
            model_name="recurringtask",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="終了日"),
        ),
        migrations.AddField(
            model_name="recurringtask",
            name="interval_type",
            field=models.CharField(
                choices=[("weeks", "週間"), ("months", "ヶ月")],
                default="months",
                max_length=10,
                verbose_name="間隔の単位",
            ),
        ),
        migrations.AddField(
            model_name="recurringtask",
            name="interval_value",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="間隔の数値"
            ),
        ),
        migrations.AddField(
            model_name="recurringtask",
            name="start_date",
            field=models.DateField(default=datetime.date.today, verbose_name="開始日"),
        ),
    ]
