"""
データマイグレーション: user=NULL の既存レコードをスーパーユーザー（is_superuser=True の最初のユーザー）に紐付ける。
本番 DB にすでにテストデータが存在する場合も安全に適用できる。
"""

# Generated by Django 5.1.15 on 2026-03-29 11:12

from django.db import migrations


def assign_to_superuser(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Subscription = apps.get_model("tracker", "Subscription")
    RecurringTask = apps.get_model("tracker", "RecurringTask")

    # スーパーユーザーが存在しない環境（CI等）ではスキップ
    superuser = User.objects.filter(is_superuser=True).order_by("id").first()
    if superuser is None:
        return

    Subscription.objects.filter(user__isnull=True).update(user=superuser)
    RecurringTask.objects.filter(user__isnull=True).update(user=superuser)


def reverse_assign(apps, schema_editor):
    # ロールバック時は user を NULL に戻す
    Subscription = apps.get_model("tracker", "Subscription")
    RecurringTask = apps.get_model("tracker", "RecurringTask")
    Subscription.objects.all().update(user=None)
    RecurringTask.objects.all().update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_add_user_fk"),
    ]

    operations = [
        migrations.RunPython(assign_to_superuser, reverse_code=reverse_assign),
    ]
